### ISSUE TITLE
Instance of FFIVariableArgument did not understand #emitArgument:context:

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-project/threadedFFI-Plugin#20]
The current version has troubles with the TTF initialization.

To reproduce just install the latest mars-gtk and save the image. 

```
FFIVariableArgument(Object)>>doesNotUnderstand: #emitArgument:context:
[ :each | each emitArgument: builder context: sender ] in TFCalloutMethodBuilder>>generateFFICallout:spec: in Block: [ :each | each emitArgument: builder context: send...etc...
OrderedCollection>>do:
TFCalloutMethodBuilder>>generateFFICallout:spec:
[ :builder | self generateFFICallout: builder spec: functionSpec ] in TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec: in Block: [ :builder | self generateFFICallout: builder spec...etc...
IRBuilder class>>buildIR:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generateMethodFromSpec:
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>generate
TFCalloutMethodBuilder(FFICalloutMethodBuilder)>>build:
TFCalloutAPI(FFICalloutAPI)>>function:library:
FreeTypeFace(Object)>>ffiCall:library:options:
FreeTypeFace(Object)>>ffiCall:library:
FreeTypeFace(Object)>>ffiCall:
FreeTypeFace(FT2Face)>>ffiOutline:embolden:
```

**Comment by pavel-krivanek** [comment]
caused by Pharo commit b839d66, threaddedFFI needs to be synchronized with the UFFI API

**Comment by guillep** [comment]
Hi Pavel, would you mind checking with the changes in #21?

**Comment by pavel-krivanek** [comment]
It is not enough. I did a same hotpatch of my image but, at least, I had to define `FFICalloutMethodBuilder>>#stringEncodingStrategy` too. I did it like
```
stringEncodingStrategy 
	^ FFILegacyStringEncodingStrategy new
```
...but I haven't studied how much correct it really is (but it seems to work)

**Comment by guillep** [comment]
That seems strange. I haven't tried setting TFFI for the whole image (which seems to be what you have...). Gimme some more minutes :)

**Comment by guillep** [comment]
I've downloaded Mars-gtk in an image with my patch and It seems to be working. My steps:
 - load new pharo8
 - load TFFI with my patch
 - load mars-gtk
 - save as Pharo.1.image
 - open Pharo.1.image

Did you do something else?

**Comment by guillep** [comment]
Did you use `self requestor` as argument of the `inCallout:` keyword?

**Comment by pavel-krivanek** [comment]
you are probably right, It seems to work. Let's merge it and I will let rebuild our full images to see if it is really fine. Thanks!

**Comment by guillep** [comment]
Cool, ping me if you find something else!

**Comment by pavel-krivanek** [comment]
it looks fixes. Once again, thank you!
