### ISSUE TITLE
Troubles with struct of doubles as function argument

### ISSUE THREAD

**Issue by tinchodias** [pharo-project/threadedFFI-Plugin#24]
Description and steps to reproduce are [here](https://github.com/pharo-project/pharo/issues/5701#issuecomment-587166900), initially discovered on uffi in Pharo project but it's also a bug for this project.

**Comment by tinchodias** [comment]
Do you think this could be fixed now? If you think so, I re-try to reproduce the issue.

**Comment by estebanlm** [comment]
in TFFI this should be fixed, yes (but it worths a verification :P)

**Comment by tinchodias** [comment]
Hi! yes, it is fixed in Pharo 10 (`curl https://get.pharo.org/64/100+vm | bash`)

**Comment by Ducasse** [comment]
So I close this issue then

**Comment by tinchodias** [comment]
To reproduce the issue I posted two tests (image+c lib). You may consider worth that I push them into the current test suite.
https://github.com/pharo-project/pharo/issues/5701
